study("MEMA & BB & Parabolic SAR", overlay = true)

// MEMA
plot(ema(close,7), title = "EMA 7", color = #2fff00, linewidth=3)
plot(ema(close,77), title = "EMA 77",  color = red, linewidth=3)
plot(ema(close,231),  title = "EMA 231", color = white, linewidth=2)

// Bollinger Bands
length = input(20, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50)
basis = ema(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
b = plot(basis, color=blue)
p1 = plot(upper, color=green)
p2 = plot(lower, color=orange)
fill(p1,p2)
//fill(p1,p2,close>upper?green:close<lower?red:cross(basis,close)?blue:yellow,100)

// Parabolic SAR
start = input(2, minval=0, maxval=10, title="Start - Default = 2 - Multiplied by .01")
increment = input(2, minval=0, maxval=10, title="Step Setting (Sensitivity) - Default = 2 - Multiplied by .01" )
maximum = input(2, minval=1, maxval=10, title="Maximum Step (Sensitivity) - Default = 2 - Multiplied by .10")
sus = input(true, "Show Up Trending Parabolic Sar")
sds = input(true, "Show Down Trending Parabolic Sar")
disc = input(false, title="Start and Step settings are *.01 so 2 = .02 etc, Maximum Step is *.10 so 2 = .2")
startCalc = start * .01
incrementCalc = increment * .01
maximumCalc = maximum * .10
sarUp = sar(startCalc, incrementCalc, maximumCalc)
sarDown = sar(startCalc, incrementCalc, maximumCalc)
colUp = close >= sarDown ? lime : na
colDown = close <= sarUp ? red : na
plot(sus and sarUp ? sarUp : na, title="Up Trending SAR", style=circles, linewidth=2,color=colUp)
plot(sds and sarDown ? sarDown : na, title="Up Trending SAR", style=circles, linewidth=2,color=colDown)
